### ISSUE TITLE
Stair left layout bug

### ISSUE THREAD

**Issue by kickingvegas** [kickingvegas/regfmt#19]
"Interrupt Mask" is truncated.

```
##
# Example YAML file for regfmt

width: 8
endian: bigBit

registers:
  - name: R1
    fields:
      - width: 1
        name: Coprocessor Usable

      - width: 1
        name: Boostrap Exception Vectors

      - width: 2
        name: Parity Errors

      - width: 4
        name: Interrupt Mask
layout:
  field-name-align: stair-left
```
