### ISSUE TITLE
YAML width with float type is processed

### ISSUE THREAD

**Issue by kickingvegas** [kickingvegas/regfmt#43]
Apparently a float value put into the `width` field is **not** flagged by the JSON validator. This is a bug.

```
# regfmt https://github.com/kickingvegas/regfmt
# ARM Coretex-M3 Program Status Register
# https://developer.arm.com/documentation/dui0552/a/the-cortex-m3-processor/programmers-model/core-registers

width: 32
endian: bigBit
layout:
  field-name-align: stair-left
registers:
- name: "APSR: Application Program Status Register"
  fields:
    - name: "N: Negative flag"
      width: 1.0
    - name: "Z: Zero flag"
      width: 1
    - name: "C: Carry or borrow flag"
      width: 1
    - name: "V: Overflow flag"
      width: 1
    - name: "Q: Saturation flag"
      width: 1
    - name: Reserved
      width: 27
```

Resulting output has float values in the field indexes.

![floatWidthBug](https://user-images.githubusercontent.com/395760/197925546-51a02d8f-02e8-4796-9f86-15e13183cd05.svg)
